### ISSUE TITLE
How To Take a Selection Screenshot (without layer-shell)

### ISSUE THREAD

**Issue by VehementHam** [project-repo/cagebreak#56] opened 2023-09-01 02:38 UTC
Is this possible?If so, what tool or workaround is requiresd?

**Comment by project-repo** [comment] 2023-09-01 10:05
Please take a look at `grim`. The archwiki page
(https://wiki.archlinux.org/title/Screen_capture#Wayland) has some
relevant information too.

**Comment by VehementHam** [comment] 2023-09-01 22:26
`grim` requires `slurp`. `slurp` requires Layer-Shell. `maim --select` works, but `maim` is being run through Xwayland, and I prefer to avoid running Xorg applications when I can. In this case it may not make a difference, though.

**Comment by project-repo** [comment] 2023-09-02 17:33
AFAIK, grim doesn't require the layer-shell protocol? According to the
man page, it is based on the screencopy protocol... In any case, I can
use grim in cagebreak to take screenshots even though we have not
implemented the layer-shell protocol. Can you reproduce this?

**Comment by VehementHam** [comment] 2023-09-03 21:42
What commands do you use?

**Comment by project-repo** [comment] 2023-09-04 07:31
So for example:
`grim -g "200,200 100x100"`.

**Comment by project-repo** [comment] 2023-09-07 17:26
Hi VehemntHam

Since this is an issue regarding usage and not primarily a bug in
Cagebreak, we are closing it for now, seeing as it hasn't seen any
activity for several days. Feel free to reopen if your issue persists.

cheers
project-repo

**Closed by project-repo** 2023-09-07 17:26 UTC

**Comment by project-repo** [comment] 2025-11-02 13:33
For future visitors: Cagebreak now supports the layer-shell protocol, so most screenshot tools (including grim and slurp) should work on Cagebreak. If not, please open a new issue.
Cheers,
project-repo
