### ISSUE TITLE
Screen/output order

### ISSUE THREAD

**Issue by kinleyd** [project-repo/cagebreak#14] opened 2021-12-07 04:22 UTC
On multi-monitor setups there is an ordering issue with regard to screens/outputs.

I have the following 4 monitor configuration:

video card configuration:

$ ls /sys/class/drm
`card0  card0-DP-1  card0-DVI-D-1  card0-DVI-I-1  card0-HDMI-A-1  card1  card1-DP-2  card1-DP-3  card1-DP-4  card1-HDMI-A-2  renderD128  renderD129  version`

sway/config setting:

output HDMI-A-1 resolution 1920x1080 position 0,0
output DVI-I-1 resolution 1920x1080 position 1920,0
output DVI-D-1 resolution 1920x1080 position 3840,0
output HDMI-A-2 resolution 3840x2160 position 5760,0

$ wayland-info | grep xdg_output -A 5

interface: 'zxdg_output_manager_v1',                     version:  3, name: 18

	xdg_output_v1
		output: 31
		name: 'HDMI-A-1'
		description: 'Goldstar Company Ltd 23EA63  (HDMI-A-1)'
		logical_x: 0, logical_y: 0
		logical_width: 1920, logical_height: 1080

	xdg_output_v1
		output: 30
		name: 'DVI-I-1'
		description: 'Goldstar Company Ltd 23EA63 312INQUC8516 (DVI-I-1 via DVI-D)'
		logical_x: 1920, logical_y: 0
		logical_width: 1920, logical_height: 1080

	xdg_output_v1
		output: 29
		name: 'DVI-D-1'
		description: 'Goldstar Company Ltd 23EA63 401INJL0F588 (DVI-D-1)'
		logical_x: 3840, logical_y: 0
		logical_width: 1920, logical_height: 1080

	xdg_output_v1
		output: 28
		name: 'HDMI-A-2'
		description: 'Sharp Corporation SHARP HDMI 0x00000000 (HDMI-A-2)'
		logical_x: 5700, logical_y: 0
		logical_width: 3840, logical_height: 2160

Cagebreak defaults:

Output location when opening first application without prevscreen/nextscreen: DVI-I-1.

Here DVI-I-1, the second logical output, is taken as the currently active output. 

Output location when opening first application after calling prevscreen: DVI-D-1 (third logical output)
Output location when opening first application after calling nextscreen: HDMI-A-1 (first logical output)

Here prevscreen and prevnext take HDMI-A-2, the fourth logical output, as the currently active output.

**Comment by project-repo** [comment] 2021-12-08 18:23
Hmmm... what happens if you call prevscreen, then nextscreen and then
open an application (and conversely first nextscreen, then prevscreen,
then open application)? If all goes well, this should open the
application on DVI-I-1.

It might also help if you could post the output of `cagebreak -s`
before you launch cagebreak (eg. from the TTY) here...

The problem is that cagebreak does not sort the outputs by "nth logical
output". Indeed it does not sort them at all and instead inserts them in
the order that they request to be added. That being said, it may well be
that the order in which cagebreak sees the outputs is:

DVI-I-1, HDMI-A-1, HDMI-A-2, DVI-D-1

which would be consistent with the output you obtain. If the procedure I
described above works as expected, then as much as I can tell nothing
out of ordinary is going on. However, once #11 is implemented,
you should be able to determine a more meaningful ordering of the
outputs which would make the behaviour of prevscreen and nextscreen more
logical.

cheers
project-repo

**Comment by kinleyd** [comment] 2021-12-09 05:24
$ cagebreak -s:

Outputs:

 * HDMI-A-2
 * HDMI-A-1
 * DVI-D-1
 * DVI-I-1

I think what's happening is that at the time cagebreak/config is executed, the monitor order is as listed above, and Cagebreak assumes HDMI-A-2 is the first monitor.

What I've found when doing the same configuration via a bash script is that the monitor order at that point is as listed under wayland-info. prevscreen/nextscreen work as expected when done that way.

In any case, as you said, once issue #11 is implemented this should all be covered very well. I look forward to that.

**Comment by project-repo** [comment] 2021-12-09 07:19
Thank you for the additional information. Glad to hear that everything seems
to behave as expected. Since this issue is now just waiting for the
implementation of #11, I am closing this.

cheers
project-repo

**Closed by project-repo** 2021-12-09 07:19 UTC
