### ISSUE TITLE
Suggestion: use scdoc instead of pandoc to generate manpages

### ISSUE THREAD

**Issue by AndersonTorres** [project-repo/cagebreak#5] opened 2021-05-05 01:13 UTC
Hello!

I am, huh, a mere package maintainer. This is a simple suggestion: use scdoc to generate manpages, instead of pandoc.

The advantages are:
- scdoc is tailored to generate manpages from markdown-like sources;
- scdoc is smaller
- scdoc has less dependencies

**Comment by project-repo** [comment] 2021-05-05 07:52
Thank you for suggesting this, we just used pandoc because the other tools considered at the time seemed worse.

We are currently testing scdoc and will use it to compile our man pages, provided nothing goes wrong, starting at the next release.

In addition, we are also considering uploading a tarball with artifacts for each release (cagebreak binary, cagebreak.1 man page and cagebreak-config.5 man page). This would further reduce the need for build dependencies to tar and gpg if the binary does not have to be built from source for package maintainer philosophy reasons. (As long as the binary is still reproducible, we might consider adding a binary with flags of your choice to make your packaging life easier)

**Comment by project-repo** [comment] 2021-05-06 12:59
Cagebreak now uses scdoc for man page compilation.

Artefacts of the release are available [here](https://github.com/project-repo/cagebreak/releases/tag/1.7.1).

[Cagebreak-pkgbuild](https://github.com/project-repo/cagebreak-pkgbuild) now uses this for the cagebreak-bin PKGBUILD and it seems to work.

@epsilon-0 are you interested in no or non-pandoc man page compilation?

I am closing this issue. Feel free to open new issues to make your packaging lives easier.

**Closed** 2021-05-06 12:59 UTC

**Comment by epsilon-0** [comment] 2021-05-07 18:53
Yes, the scdoc based generation would be the best option!
The current situation with an optional pandoc is the second best.
I love having man pages, :heart:, so if you shift to using scdoc, I will turn it on by default.

**Comment by project-repo** [comment] 2021-05-07 19:27
Sorry, our last comment might have been a bit unclear.

The current situation is that cagebreak uses scdoc instead of pandoc (since 1.7.1).

If you want zero dependencies, you can download the [artefacts tarball](https://github.com/project-repo/cagebreak/releases/download/1.7.1/release-artefacts_1.7.1.tar.gz) ([sig](https://github.com/project-repo/cagebreak/releases/download/1.7.1/release-artefacts_1.7.1.tar.gz.sig)) (also new with 1.7.1) and use the already-compiled man pages from there.
